# Generated by Django 6.0 on 2025-12-30 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="cover_image",
            field=models.ImageField(
                default="default_book.jpg", upload_to="book_covers/"
            ),
        ),
    ]
