# Generated by Django 6.0 on 2025-12-31 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0003_book_cover_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="bookreview",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="book",
            name="cover_image",
            field=models.ImageField(
                default="default_book.png", upload_to="book_covers/"
            ),
        ),
    ]
